name: plasmaburn
description: nothing but pain

base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 44

stages:
  - name: starship
    from: docker.io/library/rust:slim
    modules:
      - type: script
        snippets:
          - cargo install starship --locked
          - mkdir -p /out && mv $CARGO_HOME/bin/starship /out/

modules:
  - from-file: fedora-packages.yml 
  - from-file: copr-lact.yml
  - from-file: install-stages.yml
  - from-file: remove-deps.yml
  - from-file: files.yml
  - from-file: permissions.yml
  - from-file: services.yml
  - type: signing