#!/usr/bin/bash

KARGS=$(rpm-ostree kargs)
NEEDED_KARGS=()

# will check and set amdgpu overclock & iommu kargs on boot if they do not exist

echo "Current kargs: $KARGS"

if [[ ! $KARGS =~ "ppfeaturemask" ]]; then
    NEEDED_KARGS+=("--append-if-missing=amdgpu.ppfeaturemask=0xffffffff")
  fi

if [[ ! $KARGS =~ "intel_iommu" ]]; then
    NEEDED_KARGS+=("--append-if-missing=intel_iommu=on")
  fi

if [[ ! $KARGS =~ "iommu=pt" ]]; then
    NEEDED_KARGS+=("--append-if-missing=iommu=pt")
  fi
  
if [[ ! $KARGS =~ "module_blacklist=hid_uclogic,wacom" ]]; then
    NEEDED_KARGS+=("--append-if-missing=module_blacklist=hid_uclogic,wacom")
  fi

if [[ -n "$NEEDED_KARGS" ]]; then
  echo "Found needed karg changes, applying the following: ${NEEDED_KARGS[*]}"
  plymouth display-message --text="Updating kargs - Please wait, this may take a while" || true
  rpm-ostree kargs ${NEEDED_KARGS[*]} --reboot || exit 1
else
  echo "No karg changes needed"
fi

if [ "$(hostname)" != "plasmaburn" ]; then
  hostnamectl set-hostname plasmaburn
else
  echo "Hostname has not changed"
fi